### ISSUE TITLE
报错，请问如何解决？

### ISSUE THREAD

**Issue by rzgbw** [MengLi-l1/StrokeExtraction#4]
return {
                'target_single_stroke': target_single_image,
                'reference_single_stroke': reference_single_image,
                'target_data': target_image,
                'reference_color': reference_color_image,
                'stroke_num': stroke_num,
                'reference_single_stroke_centroid': reference_single_centroid,
                # 'seg_id': stroke_label,
                'stroke_label': stroke_label,
                
 Traceback (most recent call last):
  File "main_train.py", line 34, in <module>
    train_.train()
  File "main_train.py", line 20, in train
    self.train_sdnet.calculate_prior_information_and_qualitative(save_path='dataset_forSegNet_ExtractNet_'+self.dataset)
  File "/mnt/big_disk/gbw/projects/StrokeExtraction-master_copy/train_SDNet.py", line 360, in calculate_prior_information_and_qualitative
    transformed_reference_color, transformed_single_reference_stroke = self.__calculate_linear_transformation_inference(
  File "/mnt/big_disk/gbw/projects/StrokeExtraction-master_copy/train_SDNet.py", line 140, in __calculate_linear_transformation_inference
    linear_grid = self.sd_net.get_linear_estimation(reference_single_stroke_[0], grid_[0],
  File "/mnt/big_disk/gbw/projects/StrokeExtraction-master_copy/model/model_of_SDNet.py", line 80, in get_linear_estimation
    grid_ = torch.transpose(grids, 2, 3)
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

**Comment by MengLi-l1** [comment]
使用最新的代码就可以了

**Comment by rzgbw** [comment]
谢谢，已经解决

**Comment by rzgbw** [comment]
请问，给出一张汉字图片，如何进行推理得出最后的分割笔画？

**Comment by MengLi-l1** [comment]
整个算法由三个模型构成，在推理阶段，也是按照顺序执行。参考字是必须要提供的（想要对待提取目标字做进一步拆分，知道这个字具体是什么字显然是必须的），对于待提取笔画目标字，选择对应参考字，由SDNet获取配准信息，再由SegNet获取粗分割结果，最后由ExtractNet提取出单个笔画。这里开源的主要是算法模型代码，因此没提供实际应用的推理算法。我稍后上传一个推理代码供你参考

**Comment by rzgbw** [comment]
好的谢谢，等您上传

**Comment by MengLi-l1** [comment]
完整的推理文件已经上传了，你修改下模型参数路径应该就能用，之前实验数据和项目文件来回改了很多次，有些函数接口很难保证完全没有问题，但整体上基本完整，有问题再沟通。

**Comment by rzgbw** [comment]
感谢您。推理代码可以运行，推理的目标图片必须是数据集里面的吗，不可以用自己的汉字图片作为目标图片吗?

**Comment by MengLi-l1** [comment]
可以的，我给你的只是一个例子。我在代码做了说明，需要目标字图像，以及参考字单个笔画图像以及参考字的笔画label。这里的参考字和笔画label都是可以依据实际使用来自由设定的。当然，后续推理使用的参考字信息分布肯定需要和训练数据中的参考信息分布保持一致。参考字你可以使用任何字体，甚至都不必是准确的汉字，我在数据集中使用楷体，只是因为楷体比较通用，也比较容易获取。

**Comment by MengLi-l1** [comment]
推理的目标图片也可以是其他的，但是你得在数据集中找到对应参考字信息，每个参考字数据中都写明了这个是什么字，你自己搜索下应该就能找到，目标字图片你对应读取替换即可，只要和参考字是一个字就行。总的来说，我的项目以及数据是为了学术研究做准备，在实际应用中，并不会是这种形式。

**Comment by rzgbw** [comment]
好的，明白了，谢谢
